project:
  type: book
  

  preview: 
    browser: false
    port: 3000

book:
  title: "Trabajo_Grupal"
  author: 
  - Xumiao Cheng
  - Pau Minguet Micó
  - Javier Ribal del Río
  date-format: YY
  date: "2025"
  chapters:
    - index.qmd
    - intro.qmd
    - pages/introduccion.qmd
    - pages/analisis_interno.qmd
    - pages/analisis_externo.qmd
    - pages/summary.qmd
    - pages/prompts.qmd
    - pages/references.qmd
    - pages/code.qmd



execute:
  echo: false         # Por defecto, NO mostrar código
  warning: false
  message: false
  cache: true

lang: es

crossref:
  fig-title: "Figura"    # Prefijo en español
  tbl-title: "Tabla"



citeproc: true
bibliography: references.bib
csl: iso690.csl

format:
  html:
    theme:
      - litera
      - brand
    toc: true
    number-sections: true

  pdf:
    pdf-engine: lualatex
    documentclass: scrreprt
    number-sections: true
    code-overflow: wrap
    papersize: a4
    lof: true         # Índice de figuras (PDF)
    colorlinks: false
    template-partials:        # << reemplazamos la sección que crea la portada
    - before-body.tex


filters:
  - colour.lua


